from wx.lib.embeddedimage import PyEmbeddedImage

icon = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAADZSURBVHhe7dqxDQFhAIbhYwalISyg'
    b'EbGEWsyht8BFbQkRBQsYQmkHEnkjkjv+QuN879O8f3tf4j/FVZKi9ejTfjm8cfw70/rSeN4+'
    b'jeUANFbxDmj73XTJ6/N4B7RwABrLAWisxq042m4690/wPF+8fVP5FihwABqreAdcd4cTx58x'
    b'mE3GHB+8A77gADSWA9BYDkBjOQCN5QA0lgPQWA5AYzkAjeUANJYD0FgOQGM5AI3lADSWA9BY'
    b'DkBjOQCN5QA0lgPQWMWvxLpgfVxx+syvxFrEDyBJwarqDoO6JmrwmLtuAAAAAElFTkSuQmCC')

icon_running = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAFwSURBVHhe7duxbcMwEIVh0bukD7KL'
    b'0qTOAJnEA6R2Y+1ipM8wih5wCKzCgEmKd4+8+5tTKX0wadqA0rqu8+S4k0y3uQfYLYGU0iKX'
    b'Q3f/zLEEZLotAGS6LQBkui0AZLot+yD09vW7yuUzLbfzy7tc//d6+b5uo8lvkJ+PzySXD9M8'
    b'CM0bGB5213aTQKE4dWosAWoErT2AFkFzE6RE0P4WoEPQBkBUCBYAiAbBCgBRIFgCIHMEawBk'
    b'ilAC0OKmzBCyAeRsPwxC0RIYCaF4DxgFoWoTHAGhCgD1jpANIH9m7OoZoeQTMI+EULoEhkGo'
    b'2QOGQKjdBLtHqAVAXSMcAYCYELI6CgBRIOR2JADqDuFoANQVQgsA1A1CKwDUBUJLAKSOIPPp'
    b'WgMgbYSsNAAQLYIWAKJE0ARAdAjaAIgKwQIA0SBYASAKBEsAZI5gDYBMERgAkBlCvDAh020B'
    b'INNtASDTbQEg023uAeLlaZlucw4wTX83BiUlOB1zTQAAAABJRU5ErkJggg==')
